---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cassandra
  name: cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
      - name: cassandra
        image: ghcr.io/skr0d/cassandra_image:4.1.8a
        ports:
        - containerPort: 9042
      imagePullSecrets:
      - name: regcreds

