---
kind: Service
apiVersion: v1
metadata:
  name: cassandra
  namespace: cassandra
spec:
  selector:
    app: cassandra
  ports:
  - protocol: TCP
    port: 9042
    targetPort: 9042
  type: NodePort

